# Makefile

SRC	= stream.c
OBJ	= stream.o
BIN	= stream.exe


CC	= gcc
CFLAGS	= -fopenmp -O3
LDLIBS	=

#: $(BIN)


$(BIN): $(OBJ)
	@$(CC) $(CFLAGS) $(OBJ) -o $(BIN)   $(LDLIBS)

$(OBJ): 
	@$(CC) $(CFLAGS) -c $(SRC) -o $(OBJ)

clean:
	@rm -f $(BIN) $(OBJ)

